<?php

use Drupal\Core\Controller\ControllerBase;
use Drupal\Core\Routing\RouteMatchInterface;

/**
* Implements hook_form_alter().
*/

function first_module_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

    if ($form_id = 'user_login_form') {
        $form['#title'] = t('Login with XYZ Company info');
    }
}

/**
* Implements hook_help().
*/

function first_module_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        case "help.page.first_module":
            return t("This is testing the help hook"); 
            break; 
    }
}
