_core:
  default_config_hash: IQjf_ytthngZTAk_MU8-74VecArWD3G5g0oEH6PM6GA
toolbar_items:
  - devel.cache_clear
  - devel.route_info.item
  - devel.admin_settings_link
  - devel.event_info
  - devel.phpinfo
  - devel.route_info
  - devel.run_cron
  - devel.theme_registry
  - devel.session
