_core:
  default_config_hash: Khc28Vs_bLvkkxJ3VANkPJSDKfad7eBQ60UpIaBBoso
container_width: 1200
header_width: header_width_contained
main_width: main_width_contained
footer_width: footer_width_contained
all_icons_show: 1
facebook_url: 'https://www.facebook.com/idewdot'
twitter_url: 'https://twitter.com/dewdots'
instagram_url: 'https://www.instagram.com/google'
linkedin_url: 'https://in.linkedin.com/company/google'
youtube_url: 'https://www.youtube.com/@dew3'
vk_url: ''
whatsapp_url: ''
github_url: 'https://github.com/dewdot'
telegram_url: ''
vimeo_url: ''
slider_show: 1
slider_images: ''
slider_time: 5000
slider_dots: 'true'
slider_code: ''
font_src: local
highlight_author_comment: 0
node_author_pic: 0
node_tags: 0
copyright_text: 1
scrolltotop_on: 1
css_extra: 0
css_code: ''
bootstrapicons: 0
fontawesome_five: 0
fontawesome_six: 0
